### PR TITLE
first implementation.

### PR DESCRIPTION
**Pull request by ylecollen**

### CODE REVIEW

**Comment by giomfo** [comment]
LGTM, just need some comments about new added methods 'managePullToKick' and 'detectPullToKick'

**Comment by ara4n** [comment]
it would be good to name pull requests more specifically than 'first implementation'. As a random reviewer I can only see what's going on here by inferring it from the syios_159 source branch name...

**Comment by giomfo** [comment]
LGTM

**Comment by ylecollen** [comment]
Add the pulls to restart the events stream in the room and the recents viewcontrollers.
The event stream is restarted if
1 - the user scrolls over the roomviewcontroller bottom
2 - the user scrolls over the recentsviewcontroller top.

**Pull request merged**
